# Generated by Django 5.1.7 on 2025-03-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAgentsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='AiAgents',
        ),
    ]
