# Generated by Django 5.1.7 on 2025-03-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0002_aiagentsrequest_delete_aiagents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiagentsrequest',
            old_name='input_text',
            new_name='message',
        ),
    ]
