# Generated by Django 5.1.7 on 2025-03-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0003_rename_input_text_aiagentsrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagentsrequest',
            name='session_id',
            field=models.CharField(default='default_session', max_length=100),
        ),
    ]
